# Add ROS specific convenience functionality to the created image...
RUN if [ "${PRODUCTION}" = "0" ] ; then \
  echo "Build & source the catkin workspace from anywhere by typing 'cm'" \
  && echo "alias cm='cd ${WORKDIR} && catkin_make -j$(nproc) && rospack profile && source devel/setup.bash ; cd - > /dev/null'" >> /root/.bashrc \
  && echo "Ensure ros and the workspace environment is sourced even on docker exec" \
  && echo "source /opt/ros/${ROS_DISTRO}/setup.bash" >> /root/.bashrc \
  && echo "if [[ -f /workspace/devel/setup.bash ]]; then\n\
source /workspace/devel/setup.bash\n\
fi" >> /root/.bashrc ; \
fi
